/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import project1.Controller;
import project1.Rental;

/**
 *
 * @author Jeremiah Trahern
 */
public class Customers extends javax.swing.JFrame {

    /**
     * Creates new form Customers
     */
    private LinkedList<String> customers_fields;
    Controller c;
    public Customers(Controller c) {
        this.c = c;
        this.customers_fields=new LinkedList<String>();
        customers_fields.add("ID");
        customers_fields.add("Name");
        customers_fields.add("Address");
        initComponents();
        //populate_customer_table();
    }
  
    private void populate_customer_table(){
       //in case there is already some data in the customers_fields!
      //  this.jTable1.setModel(new DefaultTableModel(new Object[][]{},customers_fields.toArray()));
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        rentCar = new javax.swing.JButton();
        rentedCars = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        rentCar.setText("Rent Car");
        rentCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCarActionPerformed(evt);
            }
        });

        rentedCars.setText("Rented Cars");
        rentedCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentedCarsActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Name", "Telephone", "Address"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rentCar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rentedCars))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentCar)
                    .addComponent(rentedCars))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        Object[][] customers =  c.customersSearch( searchText.getText() );
        jTable1.setModel(new DefaultTableModel(customers,customers_fields.toArray()));
        
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void rentCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCarActionPerformed
        // TODO add your handling code here:
         Object o;
         int row = jTable1.getSelectedRow();
         if(row>=0){
             o = jTable1.getValueAt(row, 0);
            
             CustomerInfo detailsView=new CustomerInfo(c,(String)o);
             detailsView.setVisible(true);
        }
    }//GEN-LAST:event_rentCarActionPerformed

    private void rentedCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentedCarsActionPerformed
         Object o;
         int row = jTable1.getSelectedRow();
         if(row>=0){
             o = jTable1.getValueAt(row, 0);
            
             CustomerInfo detailsView=new CustomerInfo(c,(String)o);
             detailsView.setPane(1);
             detailsView.setVisible(true);
        }
    }//GEN-LAST:event_rentedCarsActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton rentCar;
    private javax.swing.JButton rentedCars;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchText;
    // End of variables declaration//GEN-END:variables
}
